.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-activity-list 1  "list "
.SH NAME
start\-cli\-backup\-activity\-list \- List manual backup, automatic backup, and restore activity
.SH SYNOPSIS
\fBstart\-cli backup activity list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List manual backup, automatic backup, and restore activity
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
