.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-unset-wan-ip 1  "unset-wan-ip "
.SH NAME
start\-cli\-net\-gateway\-unset\-wan\-ip \- Clear a gateway\*(Aqs pinned public IP and use the one StartOS detects
.SH SYNOPSIS
\fBstart\-cli net gateway unset\-wan\-ip\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR>
.SH DESCRIPTION
Clear a gateway\*(Aqs pinned public IP and use the one StartOS detects
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
