.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-review 1  "review "
.SH NAME
start\-cli\-backup\-review \- Commands to resolve automatic backup decisions for new services
.SH SYNOPSIS
\fBstart\-cli backup review\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to resolve automatic backup decisions for new services
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-backup\-review\-decide(1)
Resolve automatic backup decisions for a newly installed service
.TP
start\-cli\-backup\-review\-list(1)
List pending automatic backup decisions for newly installed services
