.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-job-delete 1  "delete "
.SH NAME
start\-cli\-backup\-job\-delete \- Delete an automatic backup job
.SH SYNOPSIS
\fBstart\-cli backup job delete\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR>
.SH DESCRIPTION
Delete an automatic backup job
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Automatic backup job identifier
