.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-job-list 1  "list "
.SH NAME
start\-cli\-backup\-job\-list \- List automatic backup jobs
.SH SYNOPSIS
\fBstart\-cli backup job list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List automatic backup jobs
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
