.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-job-run-now 1  "run-now "
.SH NAME
start\-cli\-backup\-job\-run\-now \- Run an automatic backup job now
.SH SYNOPSIS
\fBstart\-cli backup job run\-now\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR>
.SH DESCRIPTION
Run an automatic backup job now
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Automatic backup job identifier
