.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-set-wan-ip 1  "set-wan-ip "
.SH NAME
start\-cli\-net\-gateway\-set\-wan\-ip \- Set a gateway\*(Aqs WAN IP
.SH SYNOPSIS
\fBstart\-cli net gateway set\-wan\-ip\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR> <\fIIP\fR>
.SH DESCRIPTION
Set a gateway\*(Aqs WAN IP
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
.TP
<\fIIP\fR>
Public IPv4 address
