.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-history-discover 1  "discover "
.SH NAME
start\-cli\-backup\-history\-discover \- Discover automatic backup history stored on a backup target
.SH SYNOPSIS
\fBstart\-cli backup history discover\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fITARGET_ID\fR> <\fISERVER_ID\fR> <\fIPASSWORD\fR>
.SH DESCRIPTION
Discover automatic backup history stored on a backup target
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITARGET_ID\fR>
Backup target identifier
.TP
<\fISERVER_ID\fR>
Unique server identifier
.TP
<\fIPASSWORD\fR>
Password for backup encryption
