.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-activity 1  "activity "
.SH NAME
start\-cli\-backup\-activity \- Commands to inspect backup and restore activity
.SH SYNOPSIS
\fBstart\-cli backup activity\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to inspect backup and restore activity
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-backup\-activity\-list(1)
List manual backup, automatic backup, and restore activity
