.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-job-enable 1  "enable "
.SH NAME
start\-cli\-backup\-job\-enable \- Enable an automatic backup job
.SH SYNOPSIS
\fBstart\-cli backup job enable\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR>
.SH DESCRIPTION
Enable an automatic backup job
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Automatic backup job identifier
