.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-job-retry-target 1  "retry-target "
.SH NAME
start\-cli\-backup\-job\-retry\-target \- Reconnect an automatic backup target and resume its jobs
.SH SYNOPSIS
\fBstart\-cli backup job retry\-target\fR [\fB\-\-old\-password\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fITARGET_ID\fR> <\fIPASSWORD\fR>
.SH DESCRIPTION
Reconnect an automatic backup target and resume its jobs
.SH OPTIONS
.TP
\fB\-\-old\-password\fR \fI<OLD_PASSWORD>\fR
Previous backup password
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITARGET_ID\fR>
Backup target identifier
.TP
<\fIPASSWORD\fR>
Password for backup encryption
