.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-review-list 1  "list "
.SH NAME
start\-cli\-backup\-review\-list \- List pending automatic backup decisions for newly installed services
.SH SYNOPSIS
\fBstart\-cli backup review list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List pending automatic backup decisions for newly installed services
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
