.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-info-clear-description 1  "clear-description "
.SH NAME
start\-cli\-registry\-info\-clear\-description \- Remove the registry description
.SH SYNOPSIS
\fBstart\-cli registry info clear\-description\fR [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Remove the registry description
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
