.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-info-clear-icon 1  "clear-icon "
.SH NAME
start\-cli\-registry\-info\-clear\-icon \- Remove the registry icon
.SH SYNOPSIS
\fBstart\-cli registry info clear\-icon\fR [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
Remove the registry icon
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
