.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-targets 1  "targets "
.SH NAME
start\-cli\-backup\-targets \- List existing backup targets
.SH SYNOPSIS
\fBstart\-cli backup targets\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR]
.SH DESCRIPTION
List existing backup targets
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
