.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-backup-job-disable 1  "disable "
.SH NAME
start\-cli\-backup\-job\-disable \- Disable an automatic backup job without deleting its checkpoints
.SH SYNOPSIS
\fBstart\-cli backup job disable\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR>
.SH DESCRIPTION
Disable an automatic backup job without deleting its checkpoints
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Automatic backup job identifier
