.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-cancel-deferred-power 1  "cancel-deferred-power " 
.SH NAME
start\-cli\-server\-cancel\-deferred\-power \- Cancel a restart or shutdown that is waiting for a backup to finish
.SH SYNOPSIS
\fBstart\-cli server cancel\-deferred\-power\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Cancel a restart or shutdown that is waiting for a backup to finish
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
