.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-unset-wan-ip 1  "unset-wan-ip "
.SH NAME
start\-cli\-net\-gateway\-unset\-wan\-ip \- Use a gateway\*(Aqs detected WAN IP
.SH SYNOPSIS
\fBstart\-cli net gateway unset\-wan\-ip\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR>
.SH DESCRIPTION
Use a gateway\*(Aqs detected WAN IP
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
