// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetIpv6Params = {
  /**
   * The routed IPv6 prefix the VPS delegates to this host (e.g. a /64 from
   * Hetzner, a /56 from Linode). `null` disables tunnel IPv6.
   */
  prefix: string | null
}
