//! Descriptive-label fallback for devices that never advertise a hostname.
//!
//! Some clients deliberately withhold their name from every source
//! `devices::list` consults: ChromeOS never sends DHCP option 12 (a privacy
//! decision — only enterprise-enrolled devices with the `DeviceHostnameTemplate`
//! policy do) and doesn't answer reverse-mDNS with a friendly name; stripped-down
//! IoT DHCP clients behave the same. Rather than jump straight to the opaque
//! `device-<mac>` placeholder, this module derives a descriptive label from
//! what the device *can't* help revealing: its MAC's vendor prefix (OUI).
//!
//! Labels are derived, not learned, so they are recomputed every poll and never
//! written to the `device_names` cache — a later real hostname or a refreshed
//! vendor table wins automatically.
//!
//! Labels are English-only, matching the existing `"VPN Device"` convention in
//! `devices.rs`.

use std::collections::HashMap;
use std::io::Read;
use std::sync::LazyLock;

/// IEEE MAC-prefix registry snapshot (MA-L + MA-M + MA-S), generated by
/// `projects/start-wrt/build/gen-oui-table.sh` — see that script for
/// provenance, name-cleaning rules, and refresh instructions. Gzipped TSV,
/// one `HEXPREFIX<TAB>VENDOR` line per assignment; the prefix length encodes
/// the registry: 6 nibbles = MA-L (24-bit), 7 = MA-M (28-bit), 9 = MA-S
/// (36-bit).
static OUI_TSV_GZ: &[u8] = include_bytes!("../assets/oui.tsv.gz");

static OUI_TABLE: LazyLock<HashMap<Box<str>, Box<str>>> = LazyLock::new(|| {
    let mut text = String::new();
    match flate2::read::GzDecoder::new(OUI_TSV_GZ).read_to_string(&mut text) {
        Ok(_) => text
            .lines()
            .filter_map(|line| line.split_once('\t'))
            .map(|(prefix, vendor)| (prefix.into(), vendor.into()))
            .collect(),
        Err(e) => {
            // Unreachable short of a corrupted build; degrade to no labels.
            tracing::error!("device_ident: embedded OUI table failed to load: {e}");
            HashMap::new()
        }
    }
});

/// NIC vendor for a MAC, from the embedded IEEE registry snapshot.
///
/// Longest-prefix match (MA-S 36-bit, then MA-M 28-bit, then MA-L 24-bit) —
/// small vendors hold sub-blocks of a parent OUI, and the parent
/// ("IEEE Registration Authority") rows are excluded at generation time so an
/// unmatched sub-block falls through to `None` rather than a meaningless label.
///
/// Returns `None` for locally-administered MACs (the randomized addresses
/// modern phones/laptops use on WiFi — they have no registry entry by
/// construction) and multicast MACs.
pub fn oui_vendor(mac: &str) -> Option<&'static str> {
    let hex: String = mac
        .chars()
        .filter(char::is_ascii_alphanumeric)
        .collect::<String>()
        .to_uppercase();
    if hex.len() != 12 || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    // Bit 0 of the first octet = multicast, bit 1 = locally administered.
    let first = u8::from_str_radix(&hex[..2], 16).ok()?;
    if first & 0x03 != 0 {
        return None;
    }
    let table = LazyLock::force(&OUI_TABLE);
    [9, 7, 6]
        .into_iter()
        .find_map(|len| table.get(&hex[..len]).map(|v| &**v))
}

/// Last 6 hex digits of a MAC, lowercased — the stable per-device suffix shared
/// with `devices::fallback_name`, kept in every derived label so two unnamed
/// devices from the same vendor stay distinguishable.
pub fn mac_suffix(mac: &str) -> String {
    let hex: String = mac.chars().filter(|c| *c != ':').collect();
    let start = hex.len().saturating_sub(6);
    hex[start..].to_lowercase()
}

/// Descriptive display label for an unnamed device, e.g. `Apple device (b2c3d4)`.
/// `None` when the MAC yields no vendor (randomized MAC or unknown prefix).
pub fn device_label(mac: &str) -> Option<String> {
    oui_vendor(mac).map(|vendor| format!("{} device ({})", vendor, mac_suffix(mac)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_loads_with_all_three_registries() {
        let table = LazyLock::force(&OUI_TABLE);
        assert!(table.len() > 30_000, "table has {} entries", table.len());
        assert!(table.keys().any(|k| k.len() == 6));
        assert!(table.keys().any(|k| k.len() == 7));
        assert!(table.keys().any(|k| k.len() == 9));
    }

    #[test]
    fn ma_l_lookup() {
        assert_eq!(
            oui_vendor("B8:27:EB:12:34:56"),
            Some("Raspberry Pi Foundation")
        );
        // Case- and format-insensitive.
        assert_eq!(oui_vendor("b827eb123456"), Some("Raspberry Pi Foundation"));
    }

    #[test]
    fn ma_s_longest_prefix_wins_and_parent_is_excluded() {
        // 8C1F64AFA is an MA-S assignment; its parent MA-L block 8C1F64 is an
        // "IEEE Registration Authority" row, excluded at generation time.
        assert_eq!(
            oui_vendor("8C:1F:64:AF:A1:23"),
            Some("DATA ELECTRONIC DEVICES")
        );
        // A sub-block of the same parent that isn't assigned (002 as of the
        // 2026-08 snapshot) must yield nothing, not the parent's name.
        assert_eq!(oui_vendor("8C:1F:64:00:20:01"), None);
    }

    #[test]
    fn randomized_and_multicast_macs_have_no_vendor() {
        // 0xDA has the locally-administered bit set (randomized MAC).
        assert_eq!(oui_vendor("DA:27:EB:12:34:56"), None);
        // 01:00:5E is IPv4-multicast space.
        assert_eq!(oui_vendor("01:00:5E:12:34:56"), None);
    }

    #[test]
    fn garbage_macs_are_rejected() {
        assert_eq!(oui_vendor(""), None);
        assert_eq!(oui_vendor("B8:27:EB:12:34"), None);
        assert_eq!(oui_vendor("ZZ:27:EB:12:34:56"), None);
    }

    #[test]
    fn label_format() {
        assert_eq!(
            device_label("B8:27:EB:12:34:AB").as_deref(),
            Some("Raspberry Pi Foundation device (1234ab)")
        );
        assert_eq!(device_label("DA:27:EB:12:34:56"), None);
    }
}
