.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-set-ipv6 1  "set-ipv6 " 
.SH NAME
start\-tunnel\-set\-ipv6 \- Set the tunnel\*(Aqs routed IPv6 prefix
.SH SYNOPSIS
\fBstart\-tunnel set\-ipv6\fR [\fB\-\-prefix\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Set the tunnel\*(Aqs routed IPv6 prefix
.SH OPTIONS
.TP
\fB\-\-prefix\fR \fI<PREFIX>\fR
The routed IPv6 prefix the VPS delegates to this host (e.g. a /64 from Hetzner, a /56 from Linode). `null` disables tunnel IPv6
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
