// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlpnInfo } from './AlpnInfo'
import type { ProxyAuth } from './ProxyAuth'
import type { UpstreamCertValidation } from './UpstreamCertValidation'

export type AddSslOptions = {
  preferredExternalPort: number
  /**
   * When `true`, the OS reverse proxy adds `X-Forwarded-Proto: https`
   * and `X-Forwarded-For: <client-ip>` to incoming HTTP requests before
   * forwarding them upstream. Setting this implies HTTP-aware proxying.
   */
  addXForwardedHeaders: boolean
  /**
   * Narrows the application protocols this binding puts forward. Where the
   * container serves its own TLS it is offered these, and the client is
   * offered whatever it picks; otherwise the client is offered these
   * directly. `None` and `'reflect'` both put the client's own list forward.
   */
  alpn: AlpnInfo | null
  /**
   * Certificate validation for the OS→container TLS leg when rewrapping.
   * `None` (the default) validates against the StartOS root CA.
   */
  upstreamCertValidation?: UpstreamCertValidation
  /**
   * Optional reverse-proxy auth gate. When set, the OS reverse proxy
   * will validate the `Authorization` header on incoming HTTP requests
   * against this configuration before forwarding them upstream.
   * Unauthenticated requests get `401 Unauthorized` with an appropriate
   * `WWW-Authenticate` challenge. For `Basic`, the authenticated
   * username is forwarded to the upstream service as `X-Forwarded-User`.
   * Setting this implies HTTP-aware proxying.
   */
  auth: ProxyAuth | null
}
