// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageId } from './PackageId'

export type BackupServiceCapacityEstimate = {
  packageId: PackageId
  liveLogicalBytes: number
  retainedSnapshotCount: number
  maximumProjectedSnapshotCount: number
  scheduledRetainedBytes: number
  manualCheckpointBytes: number | null
  archivedBytes: number
  stagingHeadroomBytes: number
  lastChangedBytes: number | null
  conservativePeakExcludingManualBytes: number
}
