// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupRunState } from './BackupRunState'

export type BackupJobStatus = {
  lastScheduledAt: string | null
  lastAttemptedAt: string | null
  lastSucceededAt: string | null
  nextRunAt: string | null
  /**
   * A durable one-shot request consumed once the backup coordinator is free.
   */
  runRequested: boolean
  consecutiveFailures: number
  lastResult: BackupRunState | null
}
