// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupRunState } from './BackupRunState'
import type { BackupRunTrigger } from './BackupRunTrigger'
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageBackupReport } from './PackageBackupReport'
import type { PackageId } from './PackageId'

export type BackupRun = {
  id: Guid
  jobId: Guid
  jobName: string
  targetId: BackupTargetId
  trigger: BackupRunTrigger
  state: BackupRunState
  startedAt: string
  completedAt: string | null
  intendedServices: Array<PackageId>
  services: { [key: PackageId]: PackageBackupReport }
  error: string | null
}
