// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupJobPause =
  | { reason: 'user' }
  | { reason: 'targetUnavailable'; failures: number }
  | { reason: 'targetIdentityMismatch' }
  | { reason: 'targetUnreadable' }
  | { reason: 'reauthenticationRequired' }
