// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupJobPause } from './BackupJobPause'
import type { BackupJobStatus } from './BackupJobStatus'
import type { BackupServiceScope } from './BackupServiceScope'
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'
import type { Schedule } from './Schedule'

export type BackupJob = {
  id: Guid
  name: string
  enabled: boolean
  pause: BackupJobPause | null
  targetId: BackupTargetId
  targetInstanceId: string
  services: BackupServiceScope
  schedule: Schedule
  defaultRetention: RetentionPolicy
  retentionOverrides: { [key: PackageId]: RetentionPolicy }
  status: BackupJobStatus
  createdAt: string
  updatedAt: string
}
