// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapacityEstimate = {
  retainedSnapshotCount: number
  maximumProjectedSnapshotCount: number
  scheduledRetainedBytes: number
  manualCheckpointBytes: number
  archivedBytes: number
  stagingHeadroomBytes: number
  lastChangedBytes: number | null
  conservativePeakBytes: number
}
