// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcmeProvider } from './AcmeProvider'
import type { GatewayId } from './GatewayId'

export type CheckChallengeParams = {
  fqdn: string
  gateway: GatewayId
  /**
   * The external port the address itself is served on. Only decides whether
   * the challenge port needs a probe of its own; it is never probed here.
   */
  port: number
  acme: AcmeProvider | null
}
