// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckPortRes } from './CheckPortRes'
import type { CheckPortV6Res } from './CheckPortV6Res'

/**
 * Reachability of the port a certificate authority validates on, for a domain
 * served on some other port, which the domain's own port says nothing about.
 * A leg is null where nothing probed it: the probe errored, or — for `port_v6`
 * — the gateway has no GUA. The caller decides what each means for its
 * verdict.
 */
export type CheckChallengeRes = {
  port: CheckPortRes | null
  portV6: CheckPortV6Res | null
}
