// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckPortV6Res = {
  ip: string
  openExternally: boolean
  openInternally: boolean
}
