// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckPortV6Res } from './CheckPortV6Res'

export type CheckPortRes = {
  ip: string
  port: number
  openExternally: boolean
  openInternally: boolean
  hairpinning: boolean
  /**
   * v6 reachability of the box's GUA at this port, when the gateway has one.
   * v6 is NAT-free, so there is no hairpinning to report.
   */
  ipv6: CheckPortV6Res | null
}
