// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckPortRes } from './CheckPortRes'
import type { CheckPortV6Res } from './CheckPortV6Res'

/**
 * Reachability of the port a certificate authority validates on, for a domain
 * served on some other port. The domain's own port says nothing about it, and
 * the address refuses every connection until a certificate is issued.
 */
export type CheckChallengeRes = {
  port: CheckPortRes
  portV6: CheckPortV6Res | null
}
