// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupServiceScope } from './BackupServiceScope'
import type { BackupTargetId } from './BackupTargetId'
import type { PackageId } from './PackageId'
import type { PasswordType } from './PasswordType'
import type { RetentionPolicy } from './RetentionPolicy'
import type { Schedule } from './Schedule'

export type CreateBackupJobParams = {
  name: string
  targetId: BackupTargetId
  services: BackupServiceScope
  schedule: Schedule
  defaultRetention: RetentionPolicy
  retentionOverrides: { [key: PackageId]: RetentionPolicy }
  password: PasswordType
  /**
   * Password that encrypted the existing backup location.
   */
  oldPassword?: PasswordType
  enabled: boolean
  /**
   * Queue the job's first run after creation.
   */
  runNow: boolean
}
