// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

export type DeleteArchivedSnapshotsParams = {
  targetId: BackupTargetId
  packageId: PackageId
  snapshotIds: Array<Guid>
  password: string
  /**
   * Password that encrypted the existing backup location.
   */
  oldPassword?: string
}
