// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An `intel_pstate` energy/performance preference. Under HWP this, not the
 * governor, decides how hard a burst is chased: at `performance` the hardware
 * jumps to maximum turbo on any load.
 */
export type Epp = string
