// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupServiceScope } from './BackupServiceScope'
import type { BackupTargetId } from './BackupTargetId'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'

export type EstimateBackupCapacityParams = {
  targetId: BackupTargetId
  services: BackupServiceScope
  defaultRetention: RetentionPolicy
  retentionOverrides: { [key: PackageId]: RetentionPolicy }
  /**
   * Preserves established history policies when estimating a new schedule.
   */
  preserveExistingPolicies: boolean
}
