// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pre-V2 `StartOSBackups` folder on a backup target, with the target's free
 * space for the create-backup warning.
 */
export type LegacyBackupInfo = { available: number }
