// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityVerdict } from './CapabilityVerdict'
import type { GatewayPortMapCapabilities } from './GatewayPortMapCapabilities'
import type { GatewayType } from './GatewayType'
import type { IpInfo } from './IpInfo'

export type NetworkInterfaceInfo = {
  name: string | null
  secure: boolean | null
  ipInfo: IpInfo | null
  /**
   * The public IPv4 the operator pinned for this gateway, taking precedence
   * over the discovered `ipInfo.wanIp`. Discovery asks the router over UPnP
   * and otherwise infers the address from outbound traffic, which names the
   * wrong one wherever ingress and egress take different paths — multi-WAN
   * routing, an ISP translating egress from a pool separate from the mapped
   * inbound address, a floating ingress address with a separate egress
   * gateway. Clearing it restores the discovered address.
   */
  wanIpOverride: string | null
  type: GatewayType
  portMap: GatewayPortMapCapabilities
  /**
   * The gateway's resolver accepted our last RFC 2136 DNS UPDATE — evidence
   * from the update client (`net::dns_update`). A WireGuard gateway only
   * serves the injected `<hostname>.local` while this is `supported`, so
   * only then is the name listed on it.
   */
  dnsUpdate: CapabilityVerdict
}
