// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NutSettings } from './NutSettings'

/**
 * Stored NUT configuration and its independent enabled state.
 */
export type NutConfig = {
  /**
   * Whether StartOS should run NUT monitoring.
   */
  enabled: boolean
  /**
   * Retained server or client settings, including while monitoring is disabled.
   */
  settings: NutSettings | null
}
