// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Directly connected UPS server settings or remote NUT client settings.
 */
export type NutSettings =
  | {
      mode: 'server'
      upsName: string
      driver: string
      port: string
      monitorUsername: string
      monitorPassword: string
      listenAll: boolean
      remoteUsername: string | null
      remotePassword: string | null
      shutdownDelay: number
    }
  | {
      mode: 'client'
      upsName: string
      host: string
      port: number
      monitorUsername: string
      monitorPassword: string
      shutdownDelay: number
    }
