// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current variables reported by the configured UPS.
 */
export type NutStatus = { target: string; variables: { [key: string]: string } }
