// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackageBackupReport = {
  error: string | null
  duration_ms: number
  logical_size: number | null
  physical_size: number | null
  changed_bytes: number | null
  measured_at: string | null
}
