// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'

export type PreviewRetentionPolicyParams = {
  targetId: BackupTargetId
  packageId: PackageId
  policy: RetentionPolicy
}
