// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PasswordType } from './PasswordType'

export type ReassignBackupTargetParams = {
  id: Guid
  targetId: BackupTargetId
  password: PasswordType
  oldPassword?: PasswordType
  waitForSchedule: boolean
}
