// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

/**
 * Complete inclusion decisions for one newly installed service.
 */
export type ResolveNewServiceBackupReviewParams = {
  packageId: PackageId
  /**
   * Every current job requires an inclusion decision.
   */
  decisions: { [key: Guid]: boolean }
}
