// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

export type RestoreSelectionParams = {
  targetId: BackupTargetId
  manualIds: Array<PackageId>
  snapshots: { [key: PackageId]: Guid }
  serverId?: string
  password?: string
}
