// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetentionTier = {
  /**
   * Width of one local-time retention bucket.
   */
  intervalSeconds: number
  /**
   * How far back from the newest successful snapshot this tier covers.
   */
  coverageSeconds: number
}
