// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceSnapshot } from './ServiceSnapshot'

export type RetentionPolicyChangePreview = {
  removed: Array<ServiceSnapshot>
  estimatedReclaimedBytes: number
  affectedJobs: Array<string>
}
