// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupActivity } from './BackupActivity'
import type { BackupJob } from './BackupJob'
import type { BackupRun } from './BackupRun'
import type { BackupTargetFailureState } from './BackupTargetFailureState'
import type { Guid } from './Guid'
import type { NewServiceBackupReview } from './NewServiceBackupReview'
import type { PackageId } from './PackageId'
import type { ServiceTargetHistory } from './ServiceTargetHistory'

export type ScheduledBackupState = {
  jobs: { [key: Guid]: BackupJob }
  histories: { [key: string]: ServiceTargetHistory }
  runs: { [key: Guid]: BackupRun }
  activities: { [key: Guid]: BackupActivity }
  targetFailures: { [key: string]: BackupTargetFailureState }
  pendingServiceReviews: { [key: PackageId]: NewServiceBackupReview }
}
