// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated five-field cron schedule tied to an IANA timezone.
 */
export type Schedule = {
  /**
   * Validated five-field cron expression.
   */
  cron: string
  /**
   * Selected IANA timezone.
   */
  timezone: string
}
