// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'
import type { ServiceSnapshot } from './ServiceSnapshot'

export type ServiceTargetHistory = {
  targetId: BackupTargetId
  targetInstanceId: string
  packageId: PackageId
  timezone: string
  policy: RetentionPolicy
  feedingJobs: Array<Guid>
  snapshots: Array<ServiceSnapshot>
  archived: boolean
}
