// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullProgress } from './FullProgress'
import type { PowerAction } from './PowerAction'
import type { RestartReason } from './RestartReason'

export type ServerStatus = {
  backupProgress: FullProgress | null
  updateProgress: FullProgress | null
  shuttingDown: boolean
  restarting: boolean
  restart: RestartReason | null
  /**
   * A restart or shutdown that was asked for while a backup was running, and
   * which StartOS carries out once the backup finishes.
   */
  deferredPowerAction: PowerAction | null
}
