// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'

export type ServiceTargetRetentionPolicy = {
  targetId: BackupTargetId
  packageId: PackageId
  /**
   * Local timezone forming retention buckets.
   */
  timezone: string
  policy: RetentionPolicy
  feedingJobs: Array<Guid>
  archived: boolean
}
