// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupSource } from './BackupSource'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

export type ServiceSnapshot = {
  id: Guid
  packageId: PackageId
  packageVersion: string
  source: BackupSource
  jobId: Guid
  jobName: string
  runId: Guid
  completedAt: string
  logicalSize: number
  physicalSize: number | null
  changedBytes: number | null
  measuredAt: string
  archived: boolean
}
