// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NutConfig } from './NutConfig'

/**
 * Parameters for replacing the stored NUT configuration.
 */
export type SetNutParams = { config: NutConfig }
