// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetServerHostnameParams = {
  /**
   * The server's `.local` hostname: lowercase letters, numbers, and hyphens
   */
  hostname: string
}
