// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShutdownParams = {
  /**
   * Block until graceful teardown completes (default over the CLI; the
   * frontend omits this and gets an immediate reply). Cleared with
   * `--nowait`. The wait can't outlive the webserver teardown that follows
   * container shutdown, so the connection drops once services are stopped.
   */
  wait: boolean
  /**
   * Let a running backup finish first, rather than interrupting it. Off by
   * default, so the systemd units that drive a real power-off — which cannot
   * wait — keep their existing behavior.
   */
  afterBackup: boolean
}
