// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupServiceScope } from './BackupServiceScope'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'
import type { Schedule } from './Schedule'

export type ValidateBackupJobParams = {
  /**
   * Existing job being replaced, or `None` for a new job.
   */
  id: Guid | null
  services: BackupServiceScope
  schedule: Schedule
  defaultRetention: RetentionPolicy
  retentionOverrides: { [key: PackageId]: RetentionPolicy }
}
